### ISSUE TITLE
Production environment vs dev

### ISSUE THREAD

**Issue by BE-Code** [exciteabletom/wordle-API#2]
At the bottom of the readme, there are some commands to get started with development. How would that be different for a production environment?

**Comment by exciteabletom** [comment]
Pretty much the same, except instead of using `flask run` to start the dev server you would use a production stack.

There are a myriad of problems with the Flask dev server that make it unsuitable for an internet facing server. Such as:
- No proper HTTPS support
- No [load balancing](https://www.nginx.com/resources/glossary/load-balancing/)
- No optimisations such as [rate limiting](https://en.wikipedia.org/wiki/Rate_limiting) or [keep alive](https://en.wikipedia.org/wiki/HTTP_persistent_connection)
- No ability to setup [multiple web apps on a single port](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/)
- And many more...

An example of a production stack you can use to replace the Flask server is Gunicorn and Nginx.

A flow chart looks like this: Web request -> Nginx -> Gunicorn -> Flask

Here's a **very simplified** explanation to help you get the concepts down:

Think of Nginx as a security guard. It handles all of the traffic coming from the public internet and ensures that your application is not being swamped by too many spam requests.

Flask does not handle HTTP requests directly, it uses the [WSGI standard](https://wsgi.readthedocs.io/en/latest/what.html) to understand HTTP requests. Gunicorn acts as a translator, turning the HTTP requests into the WSGI format for Flask.

Finally, your Flask app: 
- receives the WSGI request from Gunicorn
- manipulates it as specified in your Python code
- and sends a response back up the chain: Flask -> Gunicorn -> Nginx -> internet.

If you're looking for a tutorial the [Gunicorn documentation](https://docs.gunicorn.org/en/latest/run.html) is really good.

I know this is a bit overwhelming! If you're anything like me you will find it very difficult at first, but just know that one day it will all click and you will feel like [this](https://youtu.be/6vMO3XmNXe4) :P

Best of luck!
